version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5.15
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      im:

  redis:
    image: redis:alpine3.18
    ports:
      - 6379:6379
    container_name: redis_alpine
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      im:
    command: redis-server --requirepass 123456 --appendonly yes

  mysql:
    image: bitnami/mysql:5.7.43
    ports:
      - 3306:3306
    container_name: mysql57
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      im:

networks:
  im:
    driver: bridge
